name: CI/CD Deploy to EC2 with DockerHub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ahmedrebai07/nestjs-app

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy-to-ec2:
    name: SSH & Deploy on EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: SSH and run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} << EOF
            docker pull $IMAGE_NAME
            docker stop nestjs-app || true
            docker rm nestjs-app || true
            docker run -d --name nestjs-app -p 3000:3000 $IMAGE_NAME
          EOF